require "uk_validators/version"
require "uk_validators/nino_validator"
require "uk_validators/postcode_validator"
require "uk_validators/driving_licence_validator"
require "uk_validators/passport_number_validator"
